dependencies:
- name: cargocms-client
  repository: https://chartmuseum.jx.k8s.trunksys.com
  version: 0.2.16
- name: cargocms-netcore2-element
  repository: https://chartmuseum.jx.k8s.trunksys.com
  version: 1.0.3
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
