dependencies:
- name: cargocms-client
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.2.33
- name: cargocms-netcore2-element
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.75
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
